### ISSUE TITLE
[BUG] Hyprland Settings App doesn't launch

### ISSUE THREAD

**Issue by WaltoSoft** [mylinuxforwork/hyprland-starter#36]
When I click on the gear icon in the waybar the Hyperland Settings app doesn't launch

**To Reproduce**
1. Go to the waybar
2. Click on the gear icon to open the Hyprland Settings app

**Expected behavior**
The Hyprland Settings app opens.

**Actual behavior**
Nothing happens, when I run ps -a, I can see "python" is running, but no GUI displays

**Distribution (please complete the following information):**
 - Arch Linux

**Additional context**
When installing from the main branch per the instructions, when you start Hyprland you get a black box with errors stating messages about some shadow properties that don't exist.  I corrected that per another user's suggestion and the Error went away.  However, when I click the gear icon, it seems the Hyprland Settings app launches but nothing happens.  Please help.

**Comment by RaYoLLa** [comment]
did you find way to fix that?
getting same issue

**Comment by RaYoLLa** [comment]
I kinda find the solution : 
https://github.com/mylinuxforwork/dotfiles/wiki/Installation
I installed this dotfile from mylinuxforwork
and everything works fine

**Comment by Zero-33** [comment]
+1
(running Arch as well)

**Comment by mylinuxforwork** [comment]
@Zero-33 Are you running hyprland 0.45.x and ags 2.0.x? Can you check?

**Comment by Zero-33** [comment]
damn it just uninstalled it :disappointed:   @mylinuxforwork 
Just to confirm though, I had only installed it literally today, with the latest Arch (installed today as well) and using your script of course.

....just going to reinstall for you....

**Comment by Zero-33** [comment]
@mylinuxforwork 

Confirmation - latest arch 2024.12.01, installed using archinstall script minimal setting (no DE installed), all in a VM (KVM/virt-manager)

Versions found:
hyprland = 0.45.2-3
ags = not installed :scream: 

Further info I noticed, if it will help:

Quitting hyprland taking me back to tty1, saw this:
Error - 619: Error reading events from display: Broken pipe associated with a valueired by the modulesd device: EA

Checking journalctl:
systemd 552: Starting Portal service (Hyprland configuration)
systemd 552: Started Portal service (Hyprland configuration)
# repeated for about 7 or 8 times within a minute, to then end with
systemd 552: failed to start Portal service (Hyprland configuration)

**Comment by jasonwitty** [comment]
i am also experiencing this issue

`                 x;XxXB%89b8:b8%b88:              OS    ➜  Garuda Linux x86_64
              .8Xxd                8X:.            ├   ➜  Linux 6.12.3-zen1-1-zen
            .8Xx;                    8x:.          ├ 󰏖  ➜  2063 (pacman)
          .tt8x          .d            x88;        └   ➜  fish 3.7.1
       .@8x8;          .db:              xx@;
     ,tSXX°          .bbbbbbbbbbbbbbbbbbbB8x@;    WM    ➜  Hyprland (Wayland)
   .SXxx            bBBBBBBBBBBBBBBBBBBBbSBX8;     ├ 󰀻  ➜  Papirus-Dark [GTK2/3]
 ,888S                                     pd!     ├   ➜  Bibata-Modern-Ice (24px)
8X88/                                       q      ├   ➜  alacritty 0.14.0
8X88/                                              └   ➜  FiraCode Nerd Font Mono (12pt)
GBB.
 x%88        d888@8@X@X@X88X@@XX@@X@8@X.           ├   ➜  12th Gen Intel(R) Core(TM) i9-12900KF (16) @ 5.50 GHz GHz
   dxXd    dB8b8b8B8B08bB88b998888b88x.            ├ 󰢮  ➜  NVIDIA GeForce RTX 2080 SUPER @  GHz
    dxx8o                      .@@;.               ├   ➜  3.28 GiB / 31.15 GiB (11%)
      dx88                   .t@x.                 ├ 󰓡  ➜  0 B / 31.15 GiB (0%)
        d:SS@8ba89aa67a853Sxxad.                   ├ 󰋊  ➜  188.99 GiB / 953.57 GiB (20%) - btrfs
          .d988999889889899dd.                     └   ➜  2560x1440 px @ 143.972 Hz - 600x340 mm (27.15 inches, 108.18 ppi)
                                                   └   ➜  2560x1440 px @ 143.972 Hz - 600x340 mm (27.15 inches, 108.18 ppi)
`

**Comment by mylinuxforwork** [comment]
@Zero-33 I will check as well in my VMs. It seems that the VM bug in Hyprland is still not fixed.

**Comment by Arailsu** [comment]
Got the same issue, no VM just an old Samsung laptop and a bunch of config errors on decoration.conf

**Comment by grzesiowski1223** [comment]
> Got the same issue, no VM just an old Samsung laptop and a bunch of config errors on decoration.conf

Same here with an Thinkpad X240

**Comment by jasonwitty** [comment]
my installation is also bare metal. no vm.

**Comment by jasonwitty** [comment]
~/.config/ml4w/apps/ML4W_Hyprland_Settings-x86_64.AppImage

(process:1734440): Adwaita-WARNING **: 11:09:38.968: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

**Comment by yeSpud** [comment]
It seems to be an issue with the Settings app.
When I try to run the app image directly I get the following traceback
```py
Traceback (most recent call last):
  File "/tmp/.mount_ML4W_HyLGM2i/usr/bin/ml4w-hyprland-settings.py", line 86, in do_activate
    self.initUI()
    ~~~~~~~~~~~^^
  File "/tmp/.mount_ML4W_HyLGM2i/usr/bin/ml4w-hyprland-settings.py", line 134, in initUI
    value = self.getKeywordValue(i["keyword"])
  File "/tmp/.mount_ML4W_HyLGM2i/usr/bin/ml4w-hyprland-settings.py", line 363, in getKeywordValue
    if int_val == "1":
       ^^^^^^^
UnboundLocalError: cannot access local variable 'int_val' where it is not associated with a value
```
which appears to refer to [this line here](https://github.com/mylinuxforwork/hyprland-settings/blob/a07544b6a626df2fc042fe01ac3aae60304ed2ab/usr/bin/ml4w-hyprland-settings.py#L367)

**Comment by Lorinc74** [comment]
> Got the same issue, no VM just an old Samsung laptop and a bunch of config errors on decoration.conf

SAME

**Comment by tommarekCZE** [comment]
+1
I have arch too

**Comment by mylinuxforwork** [comment]
> I have a solution. The maintainers updated the settings app just one hour ago.
> 
> They made it to work with flatpak. Install flatpak and run these commands:
> 
> ```
> # Git is required
> sudo pacman -S git
> 
> # Change into your Downloads directory
> cd ~/Downloads
> 
> # Clone the packages
> git clone --depth 1 https://github.com/mylinuxforwork/hyprland-settings.git
> 
> # Change into the folder
> cd hyprland-settings
> 
> # Install the settings app via flatpak install 
> flatpak com.ml4w.hyprlandsettings.flatpak
> ```
> 
> After this create .sh that will run the settings app via `flatpak run com.ml4w.hyprlandsettings`
> 
> _Make sure you will grant running permission to that .sh file `chmod +x script.sh`_
> 
> Then you need to configure the waybar settings pointer. So the app click event will point to that new created sh file.
> 
> https://github.com/mylinuxforwork/hyprland-starter/wiki/Waybar
> 
> Change the "on-click" parameter for the settings app to the path of the new created .sh script.

I have updated the installation instructions again. Sorry... I am still experimenting about how to handle flatpaks. 

https://github.com/mylinuxforwork/hyprland-settings

**Comment by tommarekCZE** [comment]
> I have updated the installation instructions again. Sorry... I am still experimenting about how to handle flatpaks.
 
> https://github.com/mylinuxforwork/hyprland-settings

This is okay, I just love the problem solving on linux.

I recomend to put the audio controll handler app to the hyperland starter installed. But anyways cool project.

It is just sad that many apps dosent support wayland. Like for example I had problem with CS2 and mouse locking. Or majority of screenshoot apps dosent work on wayland.
